### ISSUE TITLE
NMEA validation appears to have a bias for 'North' and 'East' coordinates

### ISSUE THREAD

**Issue by rsunderman** [Esri/nmea-for-geoevent#3]
This issue was originally reported by Samuel Richmond June 2014. Refer to his post on the product forum [here](http://forums.arcgis.com/threads/103085-NMEA-Adapter?p=394277&viewfull=1#post394277).

Validation code in the `NMEAGPRMCMessageTranslator.java` file appears to check that coordinate values are in the 'North' and 'East' quadrant of the globe - devices which report coordinates as 'South' and/or 'West' cause the adapter to reject the sentence as invalid.

**Comment by eironside** [comment]
Verified the code is not biased. E/N coordinates get positive values, S/W coordinates get negative values.
