### ISSUE TITLE
NMEA Connectors disappear from GeoEvent 10.5 when server restarts

### ISSUE THREAD

**Issue by jfrygeo** [Esri/nmea-for-geoevent#4]
@mpEsri I have 10.5 ArcGIS Server / GeoEvent Extension on a single windows 2012 Server vm federated with an ArcGIS Base deployment on another machine.

At first the connector worked, then the server restarted, and my input could not find the NMEA adapter ("Adapter Not Available"). I tried to reload the NMEA 10.4.X connector to the Site>Components>Adapters>Add Local Adapter. There was a message saying that it was successfully added.

I moved over to Site > GeoEvent > Connectors>Inputs and saw that there was an input but it contained a lot of Java string information rather than human readable labels (ie. ${com.esri.geoevent.adapter.nmea-adapter.CONNECTOR_LABEL}.... etc). Inside this connector in the edit dialogue it contained that type of JAVA string information in each of the inputs. The NMEA option in the "adapter" parameter did not appear. I deleted this input and tried to upload .jar file again. 

The third time I tried to upload the .jar file to the local adapter, GeoEvent did not recognize anything was uploaded in the ..Connectors>Inputs. 

In each of these uploads, the "deploy" folder on the server had the "nmea-adapter-10.4.0.jar" file in the folder. 

I tried uploading the "nmea-adapter-10.3.0.jar" and a similar experience happens. It works the first time, and then continues to work.

**Comment by jfrygeo** [comment]
Looks like this is related to support incident 01877530 and not just NMEA connector. Work around to get custom connectors to work is to delete contents of the cache folder on the GEE box, (C:\Program Files\ArcGIS\Server\GeoEvent\data\cache), then start geoevent. 

The custom connector then can be uploaded again.

**Comment by eironside** [comment]
I think this is fixed in latest release.
